### ISSUE TITLE
CRUD Contacts

### ISSUE THREAD

**Issue by mouimet-infinisoft** [mouimet-infinisoft/simple-source#2]
**Story Issue: Develop the `Contacts` Component for the Application**

**Description:**

Develop a new component named `Contacts` for managing and displaying a list of contacts. This component will be a part of our application's main UI and will provide functionalities like viewing all contacts, creating a new contact, updating an existing contact, and trashing (deleting) a contact.

**Requirements:**

1. **Overall Layout**:
    - The component should be divided into two main sections:
        1. A sidebar that displays a list of all contacts.
        2. A main content area that displays detailed information about the currently selected contact.

2. **Header & Footer**:
    - Use the provided `Header` and `Footer` layouts at the top and bottom of the component respectively.

3. **Sidebar**:
    - Display a button to add a new contact.
    - Display a navigation link for "All Contacts" and a link for "Trash".
    - Display a list of contacts with their name and a small profile picture or avatar. The currently selected contact should be highlighted.

4. **Main Content Area**:
    - Display the profile picture or avatar of the selected contact.
    - Show the name, job title, contact number(s), email(s), and address of the selected contact. Allow for editing these fields.
    - Provide a "Message" button.
    - Provide a delete icon to trash the contact.

5. **Modals**:
    - Implement a `ConfirmModal` that will be displayed when a user tries to trash a contact. It should have options to confirm or cancel the action.

6. **Interactions**:
    - When a contact in the sidebar is clicked, it should be highlighted and its details should be displayed in the main content area.
    - The application should log actions like click events, creations, updates, and deletions.
    - Implement the create, update, and trash functionalities using the provided `ContactSDK`.

7. **State Management**:
    - Use the provided `useBrainStack` and `core` for state management.

8. **Styling**:
    - Add a class `page-app` to the `body` when the component is mounted and remove it when the component is unmounted.
    - Implement mobile responsiveness. The sidebar should be collapsible on mobile screens.

9. **Data**:
    - Utilize the provided `contactList` for initial data.
    - The contact data structure includes fields like `id`, `status`, `thumb` (image URL), `name`, `contact`, `phones`, `address`, `jobtitle`, and `emails`.

10. **External Libraries**:
    - Use the `react-perfect-scrollbar` for smooth scrolling in the sidebar and main content area.
    - Use the `react-bootstrap` components like `Button`, `Col`, `Nav`, and `Row` for layout and styling.
    - Use the `Avatar` component to display the profile picture or avatar of contacts.
    - Use the `ChipArray` component for displaying and managing lists of emails and phone numbers.

**Mockup & Code References**:
- Please refer to the provided code for the complete implementation details, including the structure of contacts, component structure, SDK functions, and UI elements.

**Testing:**
- Ensure that the component renders correctly on both desktop and mobile views.
- Test all functionalities, including adding, updating, and trashing contacts.
- Ensure smooth scrolling in both the sidebar and main content area.
- Verify that the logger logs all the intended actions.

**Notes**:
- Make sure to handle edge cases and potential errors, especially when interacting with the state or external SDKs.
- Ensure that the UI is user-friendly and intuitive.

**Comment by OlekRia** [comment]
@mouimet-infinisoft  I guess it's already done? Please check is that works especially CRUD operations.
